#FROM python:3.9-bullseye

ARG   BASE_IMAGE=nginx
ARG   BASE_VERSION=1
FROM  ${BASE_IMAGE}:${BASE_VERSION}

ARG db_pass
ENV DB_SERVER="sb-prgr1-eastus-dbsrvr-001.database.windows.net"
ENV DB_NAME="sb-prgr1-eastus-db-001"
ENV DB_USER="libadmin"
ENV DB_PASS=${db_pass}
ENV DB_DRIVER="{ODBC Driver 17 for SQL Server}"
ENV DB_PORT="1433"

WORKDIR /usr/src/app
#COPY ./requirements.txt ./
COPY ./main.py ./
COPY ./models.py ./
COPY ./utils.py ./
COPY ./testAzureSQLConnect.py ./

#RUN pip install --no-cache-dir -r requirements.txt
RUN   export DEBIAN_FRONTEND=noninteractive \
        && apt-get update \
        && apt-get install --assume-yes --quiet --no-install-recommends \
        python3 \
        python3-dev \
        python3-pip \
        libaio1 \
        gnupg \
        && rm -rf /var/lib/apt/lists/*
RUN   export DEBIAN_FRONTEND=noninteractive \
        && apt-get update \
        && apt-get install --assume-yes --quiet --no-install-recommends \
        g++ \
        unixodbc-dev \
        vim \
        && rm -rf /var/lib/apt/lists/*

#RUN wget http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/multiarch-support_2.27-3ubuntu1.4_amd64.deb
#RUN apt-get install ./multiarch-support_2.27-3ubuntu1.4_amd64.deb

#RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
#RUN curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list 
#RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
#RUN apt-get install -y multiarch-support
#RUN apt-get install -y unixodbc-dev
#RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 
#RUN apt-get install -y unixodbc
#RUN ACCEPT_EULA=Y apt-get install -y mssql-tools
COPY  requirements.txt .
RUN   pip3 install --upgrade pip==21.0.1
RUN   pip3 install setuptools==49.6.0 \
        && pip3 install -r requirements.txt
COPY  odbc/microsoft.asc ./
COPY  odbc/mssql-release.list /etc/apt/sources.list.d/
RUN   export DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y \
        && apt-key add microsoft.asc \
        && apt-get update \
        && apt-get install --assume-yes --quiet --no-install-recommends \
        msodbcsql17=17.6.1.1-1 \
        && rm -rf /var/lib/apt/lists/*


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]